import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home({ cards }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Widget Cards</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Widgets!</a>
        </h1>

        <div className={styles.grid}>
          {cards.map((card, index) => (
              <li key={index} className={styles.card}>
                <Link href={`/${card.slug}`}>
                  <a>
                    <Image
                      src={card.cardThumbnail.url}
                      alt="Picture of the author"
                      width={50}
                      height={50}
                    />
                    <h2>{card.title}</h2>
                    <p>{card.cardSubTitle}</p>
                  </a>
                </Link>
              </li>
            ))}
        </div>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}

export async function getStaticProps() {

    const result = await fetch(`https://graphql.contentful.com/content/v1/spaces/gma4quc32grm/environments/master`,{
        method: `POST`,
        headers: {
            Authorization: `Bearer DrOaX91XAnJjeLYvsjxggaRYpaRNv4VKBHBWG13llm4`,
            'content-type': 'application/json'
        },
        body: JSON.stringify({
          query: `
            query getAllCards {
              cardsCollection(order: [cardCategory_ASC, id_ASC]) {
                items {
                  id
                  title
                  slug
                  cardSubTitle
                  cardCategory
                  cardThumbnail {
                    url
                  }
                  cardBackgroundColor
                  cardActionUrl
                  cardShow
                }
              }
            }
          `,
        })
    });

    if (!result.ok) {
      console.error(result);
      return {}
    }
    
    const { data } = await result.json();
    const cards = data.cardsCollection.items;

  return {
    props: {
      cards,
    }
  }
  /*
    query {
      cardsCollection {
        items {
          id
          title
          cardSubTitle
          cardCategory
          cardThumbnail {
            url
          }
          cardBackgroundColor
          cardActionUrl
          cardShow
        }
      }
    }
  */
}
